# Generated by Django 5.1.7 on 2025-03-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('mechanic', 'Mechanic')], default='customer', max_length=15),
        ),
    ]
