# Generated by Django 5.1.7 on 2025-03-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_card',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
